name: Build and publish documentation.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and publish the docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Build the docs
        run: |
          tox -e docs-html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BASE_BRANCH: main
          BRANCH: docs # The branch the action should deploy to.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          SINGLE_COMMIT: true
          FOLDER: build/docs-html # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
