# test_b_print_all_styles

from __future__ import annotations

from pytest import mark  # noqa: F401

from opyprint import PPStyles, print  # noqa: F401


@mark.skip("Demonstrates all the foreground styles")
def test_all_fg():
    p()
    p(PPStyles.b_blue_l1)
    p(PPStyles.b_blue)
    p(PPStyles.b_blue_d1)
    p(PPStyles.b_blue_d2)
    p(PPStyles.blue_l1)
    p(PPStyles.blue)
    p(PPStyles.blue_d1)
    p(PPStyles.blue_d2)
    p()
    p(PPStyles.b_cyan_l1)
    p(PPStyles.b_cyan)
    p(PPStyles.b_cyan_d1)
    p(PPStyles.b_cyan_d2)
    p(PPStyles.cyan_l1)
    p(PPStyles.cyan)
    p(PPStyles.cyan_d1)
    p(PPStyles.cyan_d2)
    p()
    p(PPStyles.b_green_l1)
    p(PPStyles.b_green)
    p(PPStyles.b_green_d1)
    p(PPStyles.b_green_d2)
    p(PPStyles.green_l1)
    p(PPStyles.green)
    p(PPStyles.green_d1)
    p(PPStyles.green_d2)
    p()
    p(PPStyles.b_magenta_l1)
    p(PPStyles.b_magenta)
    p(PPStyles.b_magenta_d1)
    p(PPStyles.b_magenta_d2)
    p(PPStyles.magenta_l1)
    p(PPStyles.magenta)
    p(PPStyles.magenta_d1)
    p(PPStyles.magenta_d2)
    p()
    p(PPStyles.b_pink_l1)
    p(PPStyles.b_pink)
    p(PPStyles.b_pink_d1)
    p(PPStyles.b_pink_d2)
    p(PPStyles.pink_l1)
    p(PPStyles.pink)
    p(PPStyles.pink_d1)
    p(PPStyles.pink_d2)
    p()
    p(PPStyles.b_orange_l1)
    p(PPStyles.b_orange)
    p(PPStyles.b_orange_d1)
    p(PPStyles.b_orange_d2)
    p(PPStyles.orange_l1)
    p(PPStyles.orange)
    p(PPStyles.orange_d1)
    p(PPStyles.orange_d2)
    p()
    p(PPStyles.b_red_l1)
    p(PPStyles.b_red)
    p(PPStyles.b_red_d1)
    p(PPStyles.b_red_d2)
    p(PPStyles.red_l1)
    p(PPStyles.red)
    p(PPStyles.red_d1)
    p(PPStyles.red_d2)
    p()
    p(PPStyles.b_yellow_l1)
    p(PPStyles.b_yellow)
    p(PPStyles.b_yellow_d1)
    p(PPStyles.b_yellow_d2)
    p(PPStyles.yellow_l1)
    p(PPStyles.yellow)
    p(PPStyles.yellow_d1)
    p(PPStyles.yellow_d2)
    p()
    p(PPStyles.b_grey)
    p(PPStyles.b_grey_0)
    p(PPStyles.b_grey_1)
    p(PPStyles.b_grey_2)
    p(PPStyles.b_grey_3)
    p(PPStyles.b_grey_4)
    p(PPStyles.b_grey_5)
    p(PPStyles.grey)
    p(PPStyles.grey_0)
    p(PPStyles.grey_1)
    p(PPStyles.grey_2)
    p(PPStyles.grey_3)
    p(PPStyles.grey_4)
    p(PPStyles.grey_5)


@mark.skip("Demonstrates all the background styles")
def test_all_bg():
    p()
    p(PPStyles.bg_blue)
    p(PPStyles.bg_cyan)
    p(PPStyles.bg_green)
    p(PPStyles.bg_grey)
    p(PPStyles.bg_magenta)
    p(PPStyles.bg_orange)
    p(PPStyles.bg_red)
    p(PPStyles.bg_yellow)
    p()
    p(PPStyles.bg_blue)
    p(PPStyles.bg_blue_d1)
    p(PPStyles.bg_blue_d2)
    p(PPStyles.bg_blue_d3)
    p()
    p(PPStyles.bg_cyan)
    p(PPStyles.bg_cyan_d1)
    p(PPStyles.bg_cyan_d2)
    p()
    p(PPStyles.bg_green)
    p(PPStyles.bg_green_d1)
    p(PPStyles.bg_green_d2)
    p()
    p(PPStyles.bg_grey)
    p(PPStyles.bg_grey_d1)
    p(PPStyles.bg_grey_d2)
    p(PPStyles.bg_grey_d3)
    p(PPStyles.bg_grey_d4)
    p()
    p(PPStyles.bg_magenta)
    p(PPStyles.bg_magenta_d1)
    p(PPStyles.bg_magenta_d2)
    p(PPStyles.bg_magenta_d3)
    p()
    p(PPStyles.bg_orange)
    p(PPStyles.bg_orange_d1)
    p(PPStyles.bg_orange_d2)
    p(PPStyles.bg_orange_d3)
    p()
    p(PPStyles.bg_red)
    p(PPStyles.bg_red_d1)
    p(PPStyles.bg_red_d2)
    p(PPStyles.bg_red_d3)
    p()
    p(PPStyles.bg_yellow)
    p(PPStyles.bg_yellow_d1)
    p(PPStyles.bg_yellow_d2)


def p(style=None):
    if style is None:
        print("")
    else:
        print(f" {style} ", style=style)
